### PR TITLE
Formats all code

### PR DESCRIPTION
**Pull request by andrewn**
Formats all code and adds an `npm run format-code` task to do it in future.

I've added `.prettierrc` to prefer single quotes around non-JSX strings.

I've quickly smoke-tested this and it seems to work.

### CODE REVIEW

**Comment by andrewn** [comment]
Does your editor allow you to format on save?

Alternatively a pre-commit hook could work.

**Comment by andrewn** [comment]
Husky looks like it could let us define the hooks in package.json rather than rely on everyone installing them manually: https://github.com/typicode/husky

**Comment by pixelblend** [comment]
Husky looks like an excellent solution!

**Comment by andrewn** [comment]
PRs Welcome!

**Comment by pixelblend** [comment]
😡

**Pull request merged**
